### ISSUE TITLE
Build refactor: Move signing and publishing to convention in buildSrc

### ISSUE THREAD

**Issue by JonasKunz** [elastic/elastic-otel-java#151]
We currently copy-paste the buildscript configuring the signing and publication (e.g. to `inferred-spans`).
We should use a gradle convention plugin instead.

In general, we should try to remove as much logic as possible from the `subprojects {}` call in the root project, as this makes the build difficult to understand and [is not recommended](https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins_vs_cross_configuration). We shoult stick to only doing very basic things which are guaranteed to be always the same for all projects, such as assigning the `groupid` and `version`.

**Comment by SylvainJuge** [comment]
As the artifact signature and publishing conventions are only applied in CI when actually publishing to a remote repository, the best way to test any change here is probably to
- open a PR on the upstream repo (not on a fork as we are used to)
- manually trigger the `snapshot` pipeline on buildkite with the `dry_run=true` environment variable on the branch we've created (if it's on a fork then buildkite can't build it directly).
- inspect the content of the generated artifacts on buildkite (it should contain an archive that contains signed artifacts that would have been published publicly if `dry_run=false`).

**Comment by jackshirazi** [comment]
this should go into a build readme
