### ISSUE TITLE
Generate and publish documentation

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/elastic-otel-java#154]
- integrate documentation in the global Elastic documentation
- update changelog and release notes on releases and snapshot publication

**Comment by jackshirazi** [comment]
linked https://github.com/elastic/observability-docs/issues/3558

**Comment by SylvainJuge** [comment]
Documentation is now published on github so it's partially done.

The only part that is missing here would be the release notes/changelog, or we can leave that as a separate issue and close this one which is aimed more about the availability of documetation.

**Comment by SylvainJuge** [comment]
Changelog generation was added with https://github.com/elastic/elastic-otel-java/pull/454, so there isn't anything left to do here.
