### ISSUE TITLE
GA release

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/elastic-otel-java#254]
GA release of the Elastic distro of the OTel Java SDK/API/Instrumentations

- [x] release version 1.0.0 https://github.com/elastic/elastic-otel-java/pull/388
- [x] remove tech preview status and comment(s) https://github.com/elastic/elastic-otel-java/pull/388
- [x] validate Elastic APM curated UI works with it
- [x] documentation available: https://github.com/elastic/elastic-otel-java/pull/328
  - [x] add elastic config options to the readme https://github.com/elastic/elastic-otel-java/pull/379
- [x] stack trace capture config
  - [x] define option upstream https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1414
  - [x] remove `elastic.otel.span.stack.trace.min.duration` + align with upstream config https://github.com/elastic/elastic-otel-java/pull/369
- [x] ~replace inferred spans implementation with upstream~ won't happen due to depedency on 8.16 https://github.com/elastic/elastic-otel-java/pull/370
- [x] breakdown metrics: hide or disable https://github.com/elastic/elastic-otel-java/pull/384

**Comment by jackshirazi** [comment]
Don't forget to create the 1.0.0 release and remove the tech preview comment

**Comment by jackshirazi** [comment]
Also note the List of config options in configure.md that are available from the agent but not the upstream agent needs to be filled out

**Comment by jackshirazi** [comment]
https://github.com/elastic/elastic-otel-java/releases/tag/v1.0.0
