### ISSUE TITLE
project setup in a SLSA-compliant way

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/elastic-otel-java#26]
- remove project admins that should instead be regular contributors
- add project configuration + branch protection rules to make it SLSA compliant

**Comment by SylvainJuge** [comment]
- branch protection are now applied globally thus no extra config should be required
- GH repo permissions have been aligned with existing java apm agent.

**Comment by SylvainJuge** [comment]
@elastic/observablt-robots do we need to do something else here ?
I've removed myself from the admin repos, so you should be the only admins left on the repo.

**Comment by v1v** [comment]
> do we need to do something else here ?

I've just removed the Elastic machine user with `read` access from the list of contributors to this project.

Other than that, I think everything is fine now and nothing is required from us. Thanks

**Comment by SylvainJuge** [comment]
Thanks @v1v , as there is nothing left to do here I'll close this issue.
