### ISSUE TITLE
Automate licenses update

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/elastic-otel-java#386]
For now we update the project licences by executing `./gradlew updateLicensesAndNotice` manually.

The risk is to forget about it and get obsolete licences definitions, which also means we have to open dummy PRs like #155, #281 and #381 

For now we can't use renovate `postUpgradeTasks` feature as it requires a global configuration (see #385 ) for how this could have helped apply this for dependency updates.

Few possible implementation ideas:
- add a check in build that runs `./gradlew updateLicensesAndNotice` then checks for un-commited changes in the repo with a `git` command (this won't work for dependency update PRs though)
- schedule a GH action that will automatically open a PR when an update is needed
- include those changes in the first release PR before the release artifact is created, that ensures that we update it at least whenever we release.

**Comment by v1v** [comment]
What's stopping us from using GitHub actions to generate the licenses while they discuss solving this with Renovate?

https://github.com/elastic/elastic-otel-java/pull/390/files might help. It's not yet fully finished, but it took me a couple of minutes to configure what we have done in other places and filter by branch and folders.

**Comment by v1v** [comment]
> I think it's a very good work-around for now, will it be included in every PR or is that something that we'll have to schedule on main ?

In every PR

and we could even run on `main` too if that helps, so it can create a PR back...

As you prefer

I'll work on pushing the changes and then we will validate how it goes

**Comment by JonasKunz** [comment]
Taking a step back: Do we actually need the copies of dependency licenses in our repo?
I think we do need them in the agent artifact (because there we literally include the dependencies in the jar), but that could then be simply part of the jar-task instead of having all licensesadded to the git repo?

**Comment by SylvainJuge** [comment]
I don't recall the exact terminology, but when making this project compliant with the OSS policy it was one of the requirements to have it part of the binaries that we ship.

For the source code, we also have to include the notices for those dependencies, and having them checked-in allows to double check when a license changes or when dependencies are added.

I'll link to the internal issue for the OSS publication here.

**Comment by JonasKunz** [comment]
Summary from discussion on 2024/09/02: 
We'll stop checking in the licenses in the git repo all together and will instead package them on the fly when the jar is built via gradle.
This task should then contain a check for approved licenses and fail the build if the license is not known / compliant.

I'll implement this when I'm on duty.
