### ISSUE TITLE
Publish docker images in elastic docker registry

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/elastic-otel-java#7]
proposal for the test-app in smoke tests:

`docker.elastic.co/open-telemetry/elastic-otel-java/smoke-test/test-app`

We also need to publish the agent as a docker image #6 , proposal for image name

`docker.elastic.co/open-telemetry/elastic-otel-java/agent:${version}`

**Comment by SylvainJuge** [comment]
The upstream agent is published as a docker image https://hub.docker.com/r/otel/autoinstrumentation-java/tags

This is apparently owned by the otel operator team https://cloud-native.slack.com/archives/C014L2KCTE3/p1716042725494899

**Comment by SylvainJuge** [comment]
I think what my past self meant here is that we might be able to do a bit more by publishing to elastic registry as it could allow to publish snapshots.

However I think it's definitely an extra and not strictly required, so having a docker image with the agent alone as implemented with #6 is probably enough as a first step and we should consider this as a duplicate of #6.

**Comment by jackshirazi** [comment]
closing this as a duplicate, if we decide we want other uses of the image we should open a new issue
